-- ОСНОВНАЯ СХЕМА БД

drop table if exists "Роль", "Пользователь", "Магазин", "Покупатель", "Категория", "Товар", "Заказ" cascade;

create table "Роль"
(
    id     int primary key generated by default as identity,
    "Роль" text
);

create table "Пользователь"
(
    id       int primary key generated by default as identity,
    "Логин"  text not null,
    "Пароль" text not null,
    "Роль"   int references "Роль" (id)
);

create table "Магазин"
(
    id               int primary key generated by default as identity,
    "Пользователь"   int references "Пользователь" (id),
    "Фамилия"        text not null,
    "Имя"            text not null,
    "Отчество"       text,
    "Номер телефона" text not null,
    email            text,
    post             text -- должность
);

create table "Покупатель"
(
    id               int primary key generated by default as identity,
    "Пользователь"   int references "Пользователь" (id),
    "Фамилия"        text not null,
    "Имя"            text not null,
    "Номер телефона" text not null,
    email            text,
    "Адрес"          text
);

create table "Категория"
(
    id         int primary key generated by default as identity,
    "Название" text
);

create table "Товар"
(
    id               int primary key generated by default as identity, -- он же атрибут/артикул
    "Название"       text not null unique,
    "Характеристики" text,
    "Категория"      int references "Категория" (id),
    "Цена"           float check ("Цена" >= 0),
    "Количество"     smallint check ("Количество" >= 0)
);

create table "Заказ"
(
    id           int primary key generated by default as identity,
    "Покупатель" int references "Покупатель" (id),
    "Товар"      int references "Товар" (id),
    "Количество" smallint
);
--
-- create table delivery
-- (
--     delivery_id int primary key generated by default as identity,
--     method      text
-- );
--
-- create table orders
-- (
--     order_id        int primary key generated by default as identity,
--     buyer_id        int references buyer,
--     delivery_method int references delivery -- (самовывоз/курьером)
-- );
--


-- insert into permission (role)
-- values ('editor'),
--        ('reader');
--
-- insert into category (name)
-- values ('CPU'),
--        ('GPU'),
--        ('Motherboard'),
--        ('RAM'),
--        ('SSD'),
--        ('HDD'),
--        ('Power supply'),
--        ('Computer case'),
--        ('CPU cooler');
--
-- -- insert into delivery (method)
-- -- values ('pickup'),
-- --        ('by_courier');
--
-- insert into good (name, category)
-- values ('AMD 7600', 1),
--        ('Asus B650', 3),
--        ('Nvidia RTX4060', 2),
--        ('Intel 12400F', 1);
--
-- insert into users (login, password, permission)
-- values ('123', '123', 1),
--        ('456', '456', 2),
--        ('789', '789', 2);
--
-- insert into seller (users, surname, name, patronymic, phone_number, email, post)
-- values (1, 'Шамукаев', 'Олег', 'Геннадьевич', '+7 960 356-22-10', 'nds@nds-shop.ru', 'ИП');
--
-- insert into buyer (users, surname, name, phone_number, email, address)
-- values (2, 'Каценеленбоген', 'Севастьян', '+7 980 101-35-21', 'sevastyan59@outlook.com',
--         'г. Уфа, ул. Дорожная, д. 31, кв. 82'),
--        (3, 'Агапова', 'Людмила', '+7 964 631-88-25', 'lyudmila24071985@mail.ru',
--         'г. Уфа, ул. Красноармейская, д. 7, кв. 203');
