-- ОСНОВНАЯ СХЕМА БД

drop table if exists permission, users, seller, buyer, category, good cascade;

create table permission
(
    id   int primary key generated by default as identity,
    role text
);

create table users
(
    id         int primary key generated by default as identity,
    login      text not null,
    password   text not null,
    permission int references permission (id)
);

create table seller
(
    id           int primary key generated by default as identity,
    users        int references users (id),
    surname      text not null,
    name         text not null,
    patronymic   text,
    phone_number text not null,
    email        text,
    post         text -- должность
);

create table buyer
(
    id           int primary key generated by default as identity,
    users        int references users (id),
    surname      text not null,
    name         text not null,
    phone_number text not null,
    email        text,
    address      text
);

create table category
(
    id   int primary key generated by default as identity,
    name text
);

create table good
(
    id             int primary key generated by default as identity, -- он же атрибут/артикул
    name           text not null unique,
    description    text,
    specifications text,
    category       int references category (id),
    price          float check (price >= 0),
    amount         smallint check (amount >= 0)
);
--
-- create table delivery
-- (
--     delivery_id int primary key generated by default as identity,
--     method      text
-- );
--
create table orders
(
    id    int primary key generated by default as identity,
    buyer int references buyer (id)
--     delivery_method int references delivery -- (самовывоз/курьером)
);

create table buffer
(
    id     int primary key generated by default as identity,
    orders int references orders (id),
    good   int references good (id),
    amount smallint
);

insert into permission (role)
values ('editor'),
       ('reader');

insert into category (name)
values ('CPU'),
       ('GPU'),
       ('Motherboard'),
       ('RAM'),
       ('SSD'),
       ('HDD'),
       ('Power supply'),
       ('Computer case'),
       ('CPU cooler');

-- insert into delivery (method)
-- values ('pickup'),
--        ('by_courier');

insert into good (name, category)
values ('AMD 7600', 1),
       ('Asus B650', 3),
       ('Nvidia RTX4060', 2),
       ('Intel 12400F', 1);

insert into users (login, password, permission)
values ('123', '123', 1),
       ('456', '456', 2),
       ('789', '789', 2);

insert into seller (users, surname, name, patronymic, phone_number, email, post)
values (1, 'Шамукаев', 'Олег', 'Геннадьевич', '+7 960 356-22-10', 'nds@nds-shop.ru', 'ИП');

insert into buyer (users, surname, name, phone_number, email, address)
values (2, 'Каценеленбоген', 'Севастьян', '+7 980 101-35-21', 'sevastyan59@outlook.com',
        'г. Уфа, ул. Дорожная, д. 31, кв. 82'),
       (3, 'Агапова', 'Людмила', '+7 964 631-88-25', 'lyudmila24071985@mail.ru',
        'г. Уфа, ул. Красноармейская, д. 7, кв. 203');
